project_id = "nkhfmmnxlpcqhxdeftar"

[functions.strategic-insights]
verify_jwt = false

[functions.use-case-augment]
verify_jwt = false

[functions.brand-profile-generate]
verify_jwt = false

[functions.opportunity-ai]
verify_jwt = false

[functions.creative-analyze]
verify_jwt = false
